In [54]:
import pandas as pd
import ssl

# Fix for potential SSL issues
ssl._create_default_https_context = ssl._create_unverified_context

# Dataset URL
url = "https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/main/airbnb.csv"
df = pd.read_csv(url)

In [17]:
df.columns

Index(['Unnamed: 0', 'listing_id', 'name', 'host_id', 'host_name',
       'neighbourhood_full', 'coordinates', 'room_type', 'price',
       'number_of_reviews', 'last_review', 'reviews_per_month',
       'availability_365', 'rating', 'number_of_stays', '5_stars',
       'listing_added'],
      dtype='str')

In [13]:
df.describe()

,Unnamed: 0,listing_id,host_id,number_of_reviews,reviews_per_month,availability_365,rating,number_of_stays,5_stars
count,10019.000000,1.001900e+04,1.001900e+04,10019.000000,7944.000000,10019.000000,7944.000000,7944.000000,7944.000000
mean,5009.000000,1.927634e+07,6.795923e+07,22.459727,1.353894,112.284260,4.014458,33.991541,0.718599
std,2892.380507,1.095056e+07,7.863106e+07,43.173896,1.615380,131.636043,0.575064,56.089279,0.079978
min,0.000000,3.831000e+03,2.787000e+03,0.000000,0.010000,0.000000,3.000633,1.200000,0.600026
25%,2504.500000,9.674772e+06,7.910880e+06,1.000000,0.200000,0.000000,3.520443,3.600000,0.655576
50%,5009.000000,2.007030e+07,3.165167e+07,5.000000,0.710000,44.000000,4.027965,10.800000,0.709768
75%,7513.500000,2.933864e+07,1.074344e+08,22.000000,2.000000,226.000000,4.516378,38.400000,0.763978
max,10018.000000,3.648724e+07,2.741034e+08,510.000000,16.220000,365.000000,5.181114,612.000000,0.950339

Problem 1: Borough Supply / Բնակարանների առաջարկը ըստ թաղամասերի
English: We need to know which areas of New York have the most listings. Group the data by neighbourhood_group and count the total number of listings in each.
Հայերեն: Մենք պետք է իմանանք, թե Նյու Յորքի որ թաղամասերն ունեն ամենաշատ հայտարարությունները: Խմբավորեք տվյալները ըստ թաղամասերի խմբի (neighbourhood_group) և հաշվեք յուրաքանչյուրում առկա հայտարարությունների ընդհանուր քանակը:

Problem 2: Room Type Economics / Սենյակների տեսակների տնտեսագիտությունը
English: Find the Average Price for each room_type. Sort the result from most expensive to cheapest.
Հայերեն: Գտեք Միջին գինը յուրաքանչյուր սենյակի տեսակի (room_type) համար: Դասավորեք արդյունքները ամենաթանկից մինչև ամենաէժանը:

Problem 3: The "Super-Hosts" / «Սուպեր-տանտերերը»
English: Some hosts manage multiple properties. Group by host_id and host_name, calculate the total listings for each, and show only the Top 5 hosts.
Հայերեն: Որոշ տանտերեր կառավարում են բազմաթիվ բնակարաններ: Խմբավորեք ըստ տանտիրոջ ID-ի և անվան, հաշվարկեք յուրաքանչյուրի հայտարարությունների քանակը և ցուցադրեք միայն լավագույն 5 տանտերերին:

Problem 4: Neighborhood Price Spans / Գների միջակայքը թաղամասերում
English: For each neighbourhood_group, find the Maximum, Minimum, and Median price in a single summary table.
Հայերեն: Յուրաքանչյուր թաղամասի խմբի համար գտեք Առավելագույն, Նվազագույն և Մեդիան գները մեկ ամփոփիչ աղյուսակում:

Problem 5: Popularity Contest / Հանրաճանաչության մրցույթ
English: Calculate the Total Number of Reviews for each neighbourhood_group. Which group is the most "talked about"?
Հայերեն: Հաշվարկեք հետադարձ կապի (number_of_reviews) ընդհանուր քանակը յուրաքանչյուր թաղամասի խմբի համար: Ո՞ր խումբն է ամենաշատ «քննարկվում»:

Problem 6: Manhattan Availability Audit / Մանհեթենի հասանելիության աուդիտ
English: Focus only on Manhattan. Find the Average Availability (availability_365) for each specific neighbourhood within Manhattan.
Հայերեն: Կենտրոնացեք միայն Մանհեթենի վրա: Գտեք Միջին հասանելիությունը (availability_365) Մանհեթենի յուրաքանչյուր կոնկրետ թաղամասի (neighbourhood) համար:

Problem 7: Multi-Level Pricing Strategy / Գնագոյացման բազմամակարդակ ռազմավարություն
English: Group the data by both neighbourhood_group and room_type. Calculate the Average Price and the Total Number of Reviews for every combination.
Հայերեն: Խմբավորեք տվյալները թե՛ թաղամասերի խմբի, թե՛ սենյակի տեսակի հիման վրա: Հաշվարկեք Միջին գինը և Հետադարձ կապի ընդհանուր քանակը յուրաքանչյուր համակցության համար:

Problem 8: The Value Seekers / Արժեք փնտրողները
English: For each neighbourhood_group, calculate the Average Price and the Average Number of Reviews. Then, identify the group that has the highest reviews but the lowest average price (the best "value" area).
Հայերեն: Յուրաքանչյուր թաղամասի խմբի համար հաշվարկեք Միջին գինը և Հետադարձ կապի միջին քանակը: Այնուհետև պարզեք, թե որ խումբն ունի ամենաշատ կարծիքները, բայց ամենացածր միջին գինը (ամենաշահավետ տարածքը):

Problem 9: High-Traffic Neighborhoods / Մեծ հոսք ունեցող թաղամասերը
English: Find the Average Price for every neighbourhood, but only include neighborhoods that have more than 100 listings. Sort the result by price.
Հայերեն: Գտեք Միջին գինը յուրաքանչյուր թաղամասի համար, բայց ներառեք միայն այն թաղամասերը, որոնք ունեն ավելի քան 100 հայտարարություն: Դասավորեք արդյունքն ըստ գնի:

Problem 10: The Business Host Deep-Dive / Պրոֆեսիոնալ տանտերերի վերլուծություն
English: Identify hosts who have more than 10 listings (calculated by calculated_host_listings_count). For this specific group of "Business Hosts," find their Average Price per night and the Total Revenue they generate (Price * Number of Reviews as a proxy for revenue).
Հայերեն: Բացահայտեք այն տանտերերին, ովքեր ունեն ավելի քան 10 հայտարարություն (ըստ calculated_host_listings_count-ի): Այս «պրոֆեսիոնալ տանտերերի» խմբի համար գտեք մեկ գիշերվա Միջին գինը և նրանց գեներացրած Ընդհանուր եկամուտը (օգտագործելով Գին * Կարծիքների քանակը որպես եկամտի ցուցանիշ):

In [7]:
neighbourhood_listing = df.groupby('neighbourhood_full').aggregate(total_listings=('listing_id', 'count'))
neighbourhood_listing.head()

                    total_listings
neighbourhood_full
Bronx, Allerton                  9
Bronx, Baychester                1
Bronx, Belmont                   7
Bronx, Bronxdale                 6
Bronx, Castle Hill               2

In [30]:
neighbourhood_listing = df.groupby('neighbourhood_full')['listing_id'].count().sort_values(ascending=False)
neighbourhood_listing

neighbourhood_full
Brooklyn, Bedford-Stuyvesant    777
Brooklyn, Williamsburg          766
Manhattan, Harlem               541
Brooklyn, Bushwick              502
Manhattan, Hell's Kitchen       405
                               ...
Bronx, Edenwald                   1
Bronx, Eastchester                1
Queens, Whitestone                1
Staten Island, Eltingville        1
Staten Island, Westerleigh        1
Name: listing_id, Length: 198, dtype: int64

In [26]:
neighbourhood_listing = df.groupby('neighbourhood_full').agg(total_listings=('listing_id', 'count')).sort_values(by='total_listings', ascending=False)
neighbourhood_listing

                              total_listings
neighbourhood_full
Brooklyn, Bedford-Stuyvesant             777
Brooklyn, Williamsburg                   766
Manhattan, Harlem                        541
Brooklyn, Bushwick                       502
Manhattan, Hell's Kitchen                405
...                                      ...
Bronx, Edenwald                            1
Bronx, Eastchester                         1
Queens, Whitestone                         1
Staten Island, Eltingville                 1
Staten Island, Westerleigh                 1

[198 rows x 1 columns]

In [24]:
df['neighbourhood_full'].value_counts()

neighbourhood_full
Brooklyn, Bedford-Stuyvesant      777
Brooklyn, Williamsburg            766
Manhattan, Harlem                 541
Brooklyn, Bushwick                502
Manhattan, Hell's Kitchen         405
                                 ...
Staten Island, Mariners Harbor      1
Staten Island, Great Kills          1
Staten Island, Midland Beach        1
Bronx, Eastchester                  1
Staten Island, New Springville      1
Name: count, Length: 198, dtype: int64

In [31]:
df['host_name'].value_counts()

host_name
Michael         89
David           85
Sonder (NYC)    66
Alex            52
Daniel          50
                ..
Élodie           1
Ange             1
Shir             1
Rahul            1
Darktalia        1
Name: count, Length: 4084, dtype: int64

In [55]:
df['price_str'] =  df['price']
df['price'] = df['price'].str.replace(r'\D', '', regex=True).astype(float)

In [57]:
print(df['price'].isna().sum())
print(df['price_lmb'].isna().sum())

238
238

In [56]:
df['price_lmb']=df['price_str'].map(lambda s: int(s.replace('$','')) if pd.notnull(s) else s)
#df.dropna(inplace=True)
summary_table=df.groupby('neighbourhood_full')['price'].aggregate([min,max,np.median])

print(summary_table)

                               min    max  median
neighbourhood_full
Bronx, Allerton               34.0  450.0    60.0
Bronx, Baychester             75.0   75.0    75.0
Bronx, Belmont                 NaN    NaN     NaN
Bronx, Bronxdale              35.0   79.0    47.5
Bronx, Castle Hill            38.0   86.0    62.0
...                            ...    ...     ...
Staten Island, Stapleton      43.0  125.0    70.0
Staten Island, Tompkinsville  35.0  105.0    59.0
Staten Island, Tottenville    85.0  299.0   192.0
Staten Island, West Brighton  45.0   69.0    57.0
Staten Island, Westerleigh    40.0   40.0    40.0

[198 rows x 3 columns]

In [34]:
df['price'].isna().sum()

238

In [35]:
avg_price_sorted = df.groupby('room_type')['price'].mean().sort_values(ascending=False)

avg_price_sorted

room_type
home                    243.661538
Entire home/apt         209.277833
Private room             88.116770
   Shared room           87.927536
Private                  86.302326
PRIVATE ROOM             78.645161
Shared room              62.353333
Name: price, dtype: float64

In [47]:
#=============================================================================
# Problem 3: Top Hosts / Լավագույն տանտերերը
# Optimization: Using .size() is faster than .count() when you just need row counts.
top_hosts = df.groupby(['host_id', 'host_name']).count().reset_index(name='count').sort_values('count', ascending=False).iloc[0:5]
top_hosts
# reset_index(name='count').sort_values('count', ascending=False)

        host_id       host_name  count
8195  219517861    Sonder (NYC)     66
6874  107434423      Blueground     40
4506   30283594            Kara     30
3302   16098958  Jeremy & Laura     26
2961   12243051          Sonder     21
...         ...             ...    ...
3043   13283016           Sarah      1
3042   13282162          Manuel      1
3041   13262918           Glenn      1
3040   13262455         Bridget      1
8918  274103383        Jennifer      1

[8919 rows x 3 columns]

In [49]:
problem3 = df.groupby(['host_id', 'host_name']).size().reset_index(name='total_listings')
problem3.nlargest(5, 'total_listings')

        host_id       host_name  total_listings
8195  219517861    Sonder (NYC)              66
6874  107434423      Blueground              40
4506   30283594            Kara              30
3302   16098958  Jeremy & Laura              26
2961   12243051          Sonder              21

In [58]:
#=============================================================================
# Problem 4: Price Summary / Գների ամփոփագիր
# Optimization: Using strings for 'max', 'min' and np.median for accuracy.
summary = df.groupby('neighbourhood_full')['price'].agg(['max', 'min', 'median'])
summary

                                max   min  median
neighbourhood_full
Bronx, Allerton               450.0  34.0    60.0
Bronx, Baychester              75.0  75.0    75.0
Bronx, Belmont                299.0  29.0    32.5
Bronx, Bronxdale               79.0  35.0    47.5
Bronx, Castle Hill             86.0  38.0    62.0
...                             ...   ...     ...
Staten Island, Stapleton      125.0  43.0    70.0
Staten Island, Tompkinsville  105.0  35.0    59.0
Staten Island, Tottenville    299.0  85.0   192.0
Staten Island, West Brighton   69.0  45.0    57.0
Staten Island, Westerleigh     40.0  40.0    40.0

[198 rows x 3 columns]

In [61]:
df.dtypes

Unnamed: 0              int64
listing_id              int64
name                      str
host_id                 int64
host_name                 str
neighbourhood_full        str
coordinates               str
room_type                 str
price                 float64
number_of_reviews       int64
last_review               str
reviews_per_month     float64
availability_365        int64
rating                float64
number_of_stays       float64
5_stars               float64
listing_added             str
price_str                 str
price_lmb             float64
dtype: object

In [65]:
df['price_lmb']=df['price_str'].map(lambda s: int(s.replace('$','')) if pd.notnull(s) else s)
#df.dropna(inplace=True)
summary_table=df.groupby('neighbourhood_full')['price'].agg(['min', min, np.nanmin, np.min])

summary_table

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pandas/core/groupby/generic.py:498: RuntimeWarning: All-NaN axis encountered
  f = lambda x: func(x, *args, **kwargs)

                               min   min  nanmin   min
neighbourhood_full
Bronx, Allerton               34.0  34.0    34.0  34.0
Bronx, Baychester             75.0  75.0    75.0  75.0
Bronx, Belmont                29.0   NaN    29.0  29.0
Bronx, Bronxdale              35.0  35.0    35.0  35.0
Bronx, Castle Hill            38.0  38.0    38.0  38.0
...                            ...   ...     ...   ...
Staten Island, Stapleton      43.0  43.0    43.0  43.0
Staten Island, Tompkinsville  35.0  35.0    35.0  35.0
Staten Island, Tottenville    85.0  85.0    85.0  85.0
Staten Island, West Brighton  45.0  45.0    45.0  45.0
Staten Island, Westerleigh    40.0  40.0    40.0  40.0

[198 rows x 4 columns]

In [52]:
# Problem 5: Most Talked About / Ամենաշատ քննարկվողը
df_most_talked = df.groupby('neighbourhood_full')['number_of_reviews'].sum().sort_values(ascending=False).head(1)
df_most_talked

neighbourhood_full
Brooklyn, Bedford-Stuyvesant    22795
Name: number_of_reviews, dtype: int64

In [69]:
#=============================================================================
# Problem 6: Manhattan Availability / Մանհեթենի հասանելիությունը
# Optimization: Case-insensitive search for Manhattan.
manhattan_df = df[df['neighbourhood_full'].str.contains('Manhattan', case=False, na=False)]
print(manhattan_df.shape)
avg_avail_man = manhattan_df.groupby('neighbourhood_full')['availability_365'].mean()
avg_avail_man

(4449, 19)

neighbourhood_full
Manhattan, Battery Park City       99.266667
Manhattan, Chelsea                113.059361
Manhattan, Chinatown               95.776471
Manhattan, Civic Center           120.083333
Manhattan, East Harlem            102.816514
Manhattan, East Village            74.391892
Manhattan, Financial District     207.360000
Manhattan, Flatiron District      100.684211
Manhattan, Gramercy               113.133333
Manhattan, Greenwich Village       96.011905
Manhattan, Harlem                 106.739372
Manhattan, Hell's Kitchen         131.775309
Manhattan, Inwood                 107.306122
Manhattan, Kips Bay               126.271028
Manhattan, Little Italy            98.400000
Manhattan, Lower East Side         89.780000
Manhattan, Marble Hill              0.000000
Manhattan, Midtown                148.211838
Manhattan, Morningside Heights     36.712121
Manhattan, Murray Hill            159.063063
Manhattan, NoHo                   106.125000
Manhattan, Nolita                  70.884615
Manhattan, Roosevelt Island        79.777778
Manhattan, SoHo                   104.162162
Manhattan, Stuyvesant Town        109.000000
Manhattan, Theater District       188.258065
Manhattan, Tribeca                 82.857143
Manhattan, Two Bridges             71.461538
Manhattan, Upper East Side        113.526882
Manhattan, Upper West Side        101.825316
Manhattan, Washington Heights     109.731579
Manhattan, West Village            84.578947
Name: availability_365, dtype: float64

In [72]:
#=============================================================================
# Problem 7: Reviews & Price / Կարծիքներ և գին
df_7 = df.groupby(['neighbourhood_full', 'room_type']).agg(avg_price=('price', 'mean'), total_reviews=('number_of_reviews', 'sum')).reset_index()
df_7

               neighbourhood_full        room_type   avg_price  total_reviews
0                 Bronx, Allerton  Entire home/apt  188.333333             99
1                 Bronx, Allerton     Private room   67.333333            119
2               Bronx, Baychester  Entire home/apt   75.000000             69
3                  Bronx, Belmont  Entire home/apt  299.000000             10
4                  Bronx, Belmont     Private room   44.800000             70
..                            ...              ...         ...            ...
524  Staten Island, Tompkinsville  Entire home/apt   85.000000            195
525  Staten Island, Tompkinsville     Private room   47.000000            589
526    Staten Island, Tottenville  Entire home/apt  192.000000            108
527  Staten Island, West Brighton     Private room   57.000000            103
528    Staten Island, Westerleigh     Private room   40.000000             17

[529 rows x 4 columns]

In [77]:
# Problem 8: The Best Value / Ամենաշահավետ տարբերակը

df_8 = df.groupby('neighbourhood_full').agg(avg_price=('price', 'mean'), avg_reviews=('number_of_reviews', 'mean'))
df_8 = df_8.round(0)
df_8 = df_8.sort_values(by=['avg_price', 'avg_reviews'], ascending=[True, False])

df_8

                                avg_price  avg_reviews
neighbourhood_full
Bronx, Mount Eden                    30.0        291.0
Staten Island, New Dorp Beach        36.0         18.0
Queens, Little Neck                  38.0          6.0
Bronx, Tremont                       40.0         20.0
Staten Island, Westerleigh           40.0         17.0
...                                   ...          ...
Manhattan, Flatiron District        399.0         12.0
Manhattan, Battery Park City        406.0          8.0
Bronx, Unionport                    450.0          1.0
Queens, Jamaica Estates             512.0          0.0
Staten Island, Mariners Harbor        NaN         48.0

[198 rows x 2 columns]

In [80]:

#=============================================================================
# Problem 9: Popular Neighborhoods (>100) / Հանրահայտ թաղամասեր

df_9 = df.groupby('neighbourhood_full').agg(total_listings=('listing_id', 'count'), avg_price=('price', 'mean'))
df_9 = df_9[df_9['total_listings'] > 100]
df_9.round(0)

                               total_listings  avg_price
neighbourhood_full
Brooklyn, Bedford-Stuyvesant              777       99.0
Brooklyn, Bushwick                        502       85.0
Brooklyn, Clinton Hill                    120      217.0
Brooklyn, Crown Heights                   327      110.0
Brooklyn, East Flatbush                   108       96.0
Brooklyn, Flatbush                        118       86.0
Brooklyn, Greenpoint                      210      129.0
Brooklyn, Park Slope                      106      174.0
Brooklyn, Williamsburg                    766      143.0
Manhattan, Chelsea                        219      246.0
Manhattan, East Harlem                    218      125.0
Manhattan, East Village                   370      205.0
Manhattan, Financial District             150      225.0
Manhattan, Harlem                         541      117.0
Manhattan, Hell's Kitchen                 405      213.0
Manhattan, Kips Bay                       107      220.0
Manhattan, Lower East Side                200      154.0
Manhattan, Midtown                        321      281.0
Manhattan, Murray Hill                    111      203.0
Manhattan, Upper East Side                372      187.0
Manhattan, Upper West Side                395      196.0
Manhattan, Washington Heights             190       98.0
Manhattan, West Village                   152      261.0
Queens, Astoria                           190      116.0
Queens, Long Island City                  102      119.0

In [82]:
#=============================================================================
# Problem 10: Professional Host Revenue / Պրոֆեսիոնալ տանտերերի եկամուտը
df['revenue'] = df['price'] * df['number_of_reviews']
df_10 = df.groupby(['host_id', 'host_name']).agg(
    avg_price=('price', 'mean'),
    total_revenue=('revenue', 'sum'),
    total_listings=('listing_id', 'count')
)
df_10 = df_10[df_10['total_listings'] > 10]
df_10

                              avg_price  total_revenue  total_listings
host_id   host_name
12243051  Sonder             216.700000         1405.0              21
16098958  Jeremy & Laura     217.807692         6438.0              26
19303369  Hiroki              35.583333          232.0              12
22541573  Ken                214.312500         1831.0              16
30283594  Kara               290.933333         3819.0              30
61391963  Corporate Housing  149.950000         9432.0              20
107434423 Blueground         298.225000         1788.0              40
137358866 Kazuya              50.526316         1095.0              19
190921808 John               132.181818         5303.0              12
200380610 Pranjal            294.235294          175.0              17
205031545 Red Awning         744.000000        24387.0              11
219517861 Sonder (NYC)       252.909091        49051.0              66

In [81]:
import pandas as pd
import numpy as np
import ssl

# Setup
ssl._create_default_https_context = ssl._create_unverified_context
url = "https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/main/airbnb.csv"
df = pd.read_csv(url)

# --- PRE-PROCESSING (Problem 2 Logic) ---
# Cleaning price more robustly to ensure it's numeric
df['price'] = df['price'].str.replace(r'\D', '', regex=True).astype(float)

#=============================================================================
# Problem 1: Neighbourhood Listings / Բնակարանների քանակը
# Optimization: Named aggregation is great; .head() shows the result.
neighbourhood_listing = df.groupby('neighbourhood_full').agg(total_listings=('listing_id', 'count'))

#=============================================================================
# Problem 2: Average Price / Միջին գինը
# Optimization: Sorted and stored for a clean view.
avg_price_sorted = df.groupby('room_type')['price'].mean().sort_values(ascending=False)

#=============================================================================
# Problem 3: Top Hosts / Լավագույն տանտերերը
# Optimization: Using .size() is faster than .count() when you just need row counts.
top_hosts = df.groupby(['host_id', 'host_name']).size().reset_index(name='count').sort_values('count', ascending=False)

#=============================================================================
# Problem 4: Price Summary / Գների ամփոփագիր
# Optimization: Using strings for 'max', 'min' and np.median for accuracy.
summary = df.groupby('neighbourhood_full')['price'].agg(['max', 'min', np.median])

#=============================================================================
# Problem 5: Most Talked About / Ամենաշատ քննարկվողը
# Optimization: 'Most talked about' usually refers to the total SUM of reviews.
df_most_talked = df.groupby('neighbourhood_full')['number_of_reviews'].sum().sort_values(ascending=False).head(1)

#=============================================================================
# Problem 6: Manhattan Availability / Մանհեթենի հասանելիությունը
# Optimization: Case-insensitive search for Manhattan.
manhattan_df = df[df['neighbourhood_full'].str.contains('Manhattan', case=False, na=False)]
avg_avail_man = manhattan_df.groupby('neighbourhood_full')['availability_365'].mean()

#=============================================================================
# Problem 7: Reviews & Price / Կարծիքներ և գին
df_7 = df.groupby('neighbourhood_full').agg(avg_price=('price', 'mean'), total_reviews=('number_of_reviews', 'sum'))

#=============================================================================
# Problem 8: The Best Value / Ամենաշահավետ տարբերակը
# Optimization: High reviews + Low price = Value.
df_8 = df.groupby('neighbourhood_full').agg(avg_price=('price', 'mean'), avg_reviews=('number_of_reviews', 'mean'))
df_8 = df_8.sort_values(by=['avg_price', 'avg_reviews'], ascending=[True, False])

#=============================================================================
# Problem 9: Popular Neighborhoods (>100) / Հանրահայտ թաղամասեր
# Optimization: Avoid .filter() for speed; use boolean masking on the aggregated DF.
df_9 = df.groupby('neighbourhood_full').agg(total_listings=('listing_id', 'count'), avg_price=('price', 'mean'))
df_9 = df_9[df_9['total_listings'] > 100]

#=============================================================================
# Problem 10: Professional Host Revenue / Պրոֆեսիոնալ տանտերերի եկամուտը
# Optimization: Streamlined revenue calculation and filtering.
df['revenue'] = df['price'] * df['number_of_reviews']
df_10 = df.groupby(['host_id', 'host_name']).agg(
    avg_price=('price', 'mean'),
    total_revenue=('revenue', 'sum'),
    total_listings=('listing_id', 'count')
)
df_10 = df_10[df_10['total_listings'] > 10]
df_10

                              avg_price  total_revenue  total_listings
host_id   host_name
12243051  Sonder             216.700000         1405.0              21
16098958  Jeremy & Laura     217.807692         6438.0              26
19303369  Hiroki              35.583333          232.0              12
22541573  Ken                214.312500         1831.0              16
30283594  Kara               290.933333         3819.0              30
61391963  Corporate Housing  149.950000         9432.0              20
107434423 Blueground         298.225000         1788.0              40
137358866 Kazuya              50.526316         1095.0              19
190921808 John               132.181818         5303.0              12
200380610 Pranjal            294.235294          175.0              17
205031545 Red Awning         744.000000        24387.0              11
219517861 Sonder (NYC)       252.909091        49051.0              66